apiVersion: v1
kind: Service
metadata:
  name: "{{ template "safeline.luigi" . }}"
  labels:
{{ include "safeline.labels" . | indent 4 }}
spec:
  type: {{ .Values.luigi.service.type | default "ClusterIP" }}
  ports:
    - name: luigi
      protocol: TCP
      port: {{ template "safeline.luigi.port" . }}
  selector:
{{ include "safeline.matchLabels" . | indent 4 }}
    component: luigi
