apiVersion: v1
kind: Service
metadata:
  name: "{{ template "safeline.mgt" . }}"
  labels:
{{ include "safeline.labels" . | indent 4 }}
spec:
  type: {{ .Values.mgt.service.type | default "ClusterIP" }}
  ports:
    - name: web
      port: {{ template "safeline.mgt.web.port" . }}
{{- if eq .Values.mgt.service.type "NodePort" }}
      nodePort: {{ .Values.mgt.service.web.nodePort }}
{{- end }}
    - name: api
      protocol: TCP
      port: {{ template "safeline.mgt.api.port" .}}
    - name: tcd
      protocol: TCP
      port: {{ template "safeline.mgt.tcd.port" .}}
  selector:
{{ include "safeline.matchLabels" . | indent 4 }}
    component: mgt
