{{- if not .Values.database.external.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "safeline.database" . }}-url"
  labels:
{{ include "safeline.labels" . | indent 4 }}
type: Opaque
stringData:
  MGT_PG: {{ template "safeline.database.url" . }}
  DB_ADDR: {{ template "safeline.database.url" . }}
  LUIGI_PG: {{ template "safeline.database.url" . }}
{{- end }}
