apiVersion: v1
kind: Service
metadata:
  name: "{{ template "safeline.tengine" . }}"
  labels:
{{ include "safeline.labels" . | indent 4 }}
spec:
  type: {{ .Values.tengine.service.type | default "ClusterIP" }}
  {{- if and (eq .Values.tengine.service.type "LoadBalancer") .Values.tengine.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.tengine.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: health
      protocol: TCP
      port: {{ template "safeline.tengine.health.port" . }}
    - name: http
      protocol: TCP
      port: {{ template "safeline.tengine.http.port" . }}
    - name: tasktcd
      protocol: TCP
      port: {{ template "safeline.tengine.tasktcd.port" . }}
  selector:
{{ include "safeline.matchLabels" . | indent 4 }}
    component: tengine
